version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: logdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d logdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingestion:
    build: ./ingestion
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/logdb
      ML_PREDICT_URL: http://ml:8001/predict
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    depends_on:
      postgres:
        condition: service_healthy
      ml:
        condition: service_started

  ml:
    build: ./ml
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/logdb
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
    volumes:
      - ./ml:/app
      - ./data/raw:/data

  dashboard:
    build: ./dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/logdb
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    depends_on:
      postgres:
        condition: service_healthy

  generator:
    build: ./generator
    environment:
      API_URL: http://ingestion:8000/logs
      LOG_SOURCE: synthetic
      LOGHUB_FILE_PATH: /data/NASA_access_log_Jul95
      LOGHUB_MAX_LINES: "0"
    volumes:
      - ./data/raw:/data
    depends_on:
      - ingestion

volumes:
  pgdata:
