apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: log-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: log-anomaly-dashboard-ingestion:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: ML_PREDICT_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ML_PREDICT_URL
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ALLOWED_ORIGINS
            - name: SLACK_ALERT_COOLDOWN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SLACK_ALERT_COOLDOWN_SECONDS
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SLACK_WEBHOOK_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: log-anomaly
spec:
  selector:
    app: ingestion
  ports:
    - port: 8000
      targetPort: 8000
