apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  namespace: log-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: log-anomaly-dashboard-generator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: API_URL
              value: "http://ingestion:8000/logs"
            - name: LOG_SOURCE
              value: "synthetic"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
