apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: log-anomaly
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: log-anomaly-dashboard-ml:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "migrate.py"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
